# zen flavor for Yazi
# https://github.com/nendix/zen.nvim
#todo: doc
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[mgr]
cwd = { fg = "#9e9e9e" }

# Hovered
hovered         = { bg = "#222222" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#d46a6a", underline = true }
find_position = { fg = "#c5cddb", bg = "reset"}

# Marker
marker_copied   = { fg = "#a0b9a0", bg = "#a0b9a0" }
marker_cut      = { fg = "#b9a0a0", bg = "#b9a0a0" }
marker_marked   = { fg = "#a0b0b0", bg = "#a0b0b0" }
marker_selected = { fg = "#b0a0b9", bg = "#b0a0b9" }

# Count
count_copied   = { fg = "#1c1d1f", bg = "#a0b9a0" }
count_cut      = { fg = "#1c1d1f", bg = "#b9a0a0" }
count_selected = { fg = "#1c1d1f", bg = "#b0a0b9" }

# Border
border_symbol = "│"
border_style  = { fg = "#6d717a" }

[tabs]
active   = { fg = "#c5cddb", bg = "#6d717a", bold = true }
inactive = { fg = "#767676", bg = "#1a1a1a" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#1c1d1f", bg = "#c5cddb", bold = true }
normal_alt  = { fg = "#2e3133", bg = "#6d717a" }

select_main = { fg = "#1c1d1f", bg = "#b0a0b9", bold = true }
select_alt  = { fg = "#b0a0b9", bg = "#6d717a" }

unset_main = { fg = "#1c1d1f", bg = "#b9a0a0", bold = true }
unset_alt  = { fg = "#b9a0a0", bg = "#6d717a" }

[status]
overall   = { fg = "#9e9e9e" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[app]
overall = {bg = "#1c1d1f"}

[indicator]
padding = {open = "", close = ""}
current = {bg = "#c5cddb", fg = "#1C1D1F"}
parent = {bg = "#c5cddb", fg = "#1C1D1F"}

# Permissions
perm_sep   = { fg = "#767676" }
perm_type  = { fg = "#a0a0b9" }
perm_read  = { fg = "#a0b9a0" }
perm_write = { fg = "#b9a0a0" }
perm_exec  = { fg = "#b9b0a0" }

# Progress
progress_label  = { fg = "#c5cddb", bold = true }
progress_normal = { fg = "#a0b9a0", bg = "#6d717a" }
progress_error  = { fg = "#c07070", bg = "#6d717a" }

[which]
cols            = 3
mask            = { bg = "#1a1a1a" }
cand            = { fg = "#a0b0b0" }
rest            = { fg = "#767676" }
desc            = { fg = "#9e9e9e" }
separator       = "  "
separator_style = { fg = "#767676" }

[confirm]
border     = { fg = "#6d717a" }
title      = { fg = "#c5cddb" }
content    = { fg = "#c5cddb" }
list       = { fg = "#6d717a" }
btn_yes    = { fg = "#1c1d1f", bg = "#a0b9a0" }
btn_no     = { fg = "#1c1d1f", bg = "#b9a0a0" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border   = { fg = "#6d717a" }
title    = { fg = "#c5cddb" }
tbl_col  = { fg = "#c5cddb"}
tbl_cell = { fg = "#c5cddb", bg = "#1c1d1f", reversed = true }

[notify]
title_info  = { fg = "#6090a0" }
title_warn  = { fg = "#a09060" }
title_error = { fg = "#c07070" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

[pick]
border   = { fg = "#6d717a" }
active   = { fg = "#c5cddb", bg = "#6d717a", bold = true }
inactive = { fg = "#9e9e9e" }

[input]
border   = { fg = "#6d717a" }
title    = { fg = "#c5cddb" }
value    = { fg = "#c5cddb" }
selected = { reversed = true }

[cmp]
border   = { fg = "#6d717a" }
active   = { reversed = true }
inactive = { fg = "#9e9e9e" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#6d717a" }
title   = { fg = "#c5cddb" }
hovered = { fg = "#b0a0b9", bold = true }

[help]
on      = { fg = "#a0b0b0" }
run     = { fg = "#b0a0b9" }
desc    = { fg = "#9e9e9e" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#767676", bg = "#1a1a1a" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#b9b0a0" },
	# Media
	{ mime = "{audio,video}/*", fg = "#b0a0b9" },
	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#b9a0a0" },
	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#a0b0b0" },
	# Fallback
	{ name = "*", is = "orphan", bg = "#c07070" },
	{ name = "*", is = "exec", fg = "#a0b9a0" },
	{ name = "*/", fg = "#d46a6a" }
]

[ icon ] 
conds = [
   { if = "dir", text = "󰉋", fg = "#d46a6a" }
]
dirs = [
   { name = "desktop", text = "󰇄", fg = "#d46a6a" },
   { name = "downloads", text = "", fg = "#d46a6a" },
   { name = "recordings", text = "", fg = "#d46a6a" },
   { name = "screenshots", text = "", fg = "#d46a6a" },
   { name = "musics", text = "󰎇", fg = "#d46a6a" },
   { name = ".config", text = "", fg = "#d46a6a" },
   { name = "greenhouse", text = "󰧱", fg = "#d46a6a" }
]
